### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by johnjtran** [ELAScience/AQ-drone#2]
@SConaway @kbenavente we need to update the README should include the following:

- [x] How to build (Instructions)
- [x] Parts list

**Comment by SConaway** [comment]
I'll get on this once I'm back. Shouldn't take very long at all. Where would you like those sections added?

**Comment by johnjtran** [comment]
I would just put them in there and would model it after then Rovie project.  We can edit the `README` as we move forward.

**Comment by SConaway** [comment]
@johnjtran 

If you can, please give everything a once over.
