### ISSUE TITLE
Missing Prices for Parts List Items

### ISSUE THREAD

**Issue by SConaway** [ELAScience/AQ-drone#3]
These items are missing prices in the [parts list](https://github.com/ELAScience/AQ-drone/blob/master/hardware/README.md#parts-list):
* [DJI Zenmuse X3](https://store.dji.com/product/zenmuse-x3-gimbal-camera)
* [DJI Matrice 600 Upper Expansion Bay Kit](https://store.dji.com/product/matrice-600-upper-expansion-bay-kit)

They were listed as `Not available in your country/region` on DJI's web store, which is odd, as that's where we purchased them originally.

**Comment by johnjtran** [comment]
Well, maybe we can just list them for now?

**Comment by SConaway** [comment]
Ok. Will do.
